name: Build and Test PR
on: [pull_request, workflow_dispatch]
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
      - run: git diff -u
      - run: pnpm install --frozen-lockfile

      - run: pnpm build
