name: Build, Test and Publish
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'feature/**'
      - 'feat/**'
      - 'fix/**'
      - 'fixes/**'

jobs:
  build-test-publish:
    env:
      NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      GH_USER: ${{secrets.GH_USER}}
      GH_EMAIL: ${{secrets.GH_EMAIL}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.7
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build

      - name: setup git coordinates
        run: |
          git remote set-url origin https://Sphereon-Opensource:$GH_TOKEN@github.com/Sphereon-Opensource/UI-Components.git
          git config user.name $GH_USER
          git config user.email $GH_EMAIL

      - name: setup npm registry
        run: |
          echo "@sphereon:registry=https://registry.npmjs.org/" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
#          npm whoami

      - run: git diff -u

      - name: publish @latest when on main
        if: github.ref == 'refs/heads/main'
        run: pnpm publish:latest

      - name: publish @next when on develop
        if: github.ref == 'refs/heads/develop'
        run: pnpm publish:next

      - name: publish @next when on fix branch
        if: startsWith(github.ref, 'refs/heads/fix')
        run: pnpm publish:next

      - name: publish @unstable when on unstable branch
        if: startsWith(github.ref, 'refs/heads/feat')
        run: pnpm publish:unstable
